import Head from 'next/head'
import React from 'react'

const Layout = ( { children }: { children: React.ReactNode } ) => {
    return(
        <>
            <Head>
                <title>Create Next</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            { children }
        </>
        
    )
}

export default Layout;